import type {
  User,
  School,
  Teacher,
  Student,
  Parent,
  Class,
  Subject,
  Attendance,
  Exam,
  Grade,
  Subscription,
  TimetableEntry,
} from "./type"

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "John Super",
    email: "super@edumanage.com",
    role: "super_admin",
    avatar: "/admin-avatar.png",
  },
  {
    id: "u2",
    name: "Sarah Admin",
    email: "admin@school1.com",
    role: "admin",
    schoolId: "s1",
    avatar: "/female-admin.jpg",
  },
  {
    id: "u3",
    name: "Michael Teacher",
    email: "teacher@school1.com",
    role: "teacher",
    schoolId: "s1",
    avatar: "/male-teacher.png",
  },
  {
    id: "u4",
    name: "Emma Student",
    email: "student@school1.com",
    role: "student",
    schoolId: "s1",
    avatar: "/diverse-female-student.png",
  },
  {
    id: "u5",
    name: "Robert Parent",
    email: "parent@email.com",
    role: "parent",
    schoolId: "s1",
    avatar: "/male-parent.jpg",
  },
]

export const mockSchools: School[] = [
  {
    id: "s1",
    name: "Springfield High School",
    address: "123 Education Lane, Springfield",
    phone: "+1 555-0100",
    email: "info@springfieldhigh.edu",
    subscriptionPlan: "premium",
    subscriptionStatus: "active",
    subscriptionEndDate: "2025-12-31",
    studentCount: 1250,
    teacherCount: 85,
    createdAt: "2023-01-15",
  },
  {
    id: "s2",
    name: "Riverside Academy",
    address: "456 Academy Drive, Riverside",
    phone: "+1 555-0200",
    email: "contact@riversideacademy.edu",
    subscriptionPlan: "standard",
    subscriptionStatus: "active",
    subscriptionEndDate: "2025-06-30",
    studentCount: 820,
    teacherCount: 52,
    createdAt: "2023-03-20",
  },
  {
    id: "s3",
    name: "Oakwood Elementary",
    address: "789 Oak Street, Oakwood",
    phone: "+1 555-0300",
    email: "hello@oakwoodelementary.edu",
    subscriptionPlan: "basic",
    subscriptionStatus: "trial",
    subscriptionEndDate: "2025-01-15",
    studentCount: 450,
    teacherCount: 28,
    createdAt: "2024-11-01",
  },
  {
    id: "s4",
    name: "Central High School",
    address: "321 Central Ave, Downtown",
    phone: "+1 555-0400",
    email: "admin@centralhigh.edu",
    subscriptionPlan: "premium",
    subscriptionStatus: "expired",
    subscriptionEndDate: "2024-11-30",
    studentCount: 980,
    teacherCount: 65,
    createdAt: "2022-08-10",
  },
]

export const mockTeachers: Teacher[] = [
  {
    id: "t1",
    userId: "u3",
    name: "Michael Johnson",
    email: "m.johnson@school.com",
    phone: "+1 555-1001",
    department: "Mathematics",
    subjects: ["Mathematics", "Physics"],
    classes: ["Grade 9-A", "Grade 10-B"],
    joinDate: "2020-08-15",
    status: "active",
    avatar: "/male-teacher-math.jpg",
  },
  {
    id: "t2",
    userId: "u6",
    name: "Jennifer Williams",
    email: "j.williams@school.com",
    phone: "+1 555-1002",
    department: "English",
    subjects: ["English", "Literature"],
    classes: ["Grade 9-A", "Grade 9-B"],
    joinDate: "2019-07-20",
    status: "active",
    avatar: "/female-teacher-english.jpg",
  },
  {
    id: "t3",
    userId: "u7",
    name: "David Brown",
    email: "d.brown@school.com",
    phone: "+1 555-1003",
    department: "Science",
    subjects: ["Biology", "Chemistry"],
    classes: ["Grade 10-A", "Grade 11-A"],
    joinDate: "2021-01-10",
    status: "active",
    avatar: "/male-teacher-science.jpg",
  },
  {
    id: "t4",
    userId: "u8",
    name: "Lisa Anderson",
    email: "l.anderson@school.com",
    phone: "+1 555-1004",
    department: "History",
    subjects: ["History", "Geography"],
    classes: ["Grade 11-B", "Grade 12-A"],
    joinDate: "2018-09-01",
    status: "on_leave",
    avatar: "/female-history-teacher.png",
  },
]

export const mockStudents: Student[] = [
  {
    id: "st1",
    userId: "u4",
    name: "Emma Thompson",
    email: "emma.t@student.com",
    rollNumber: "STU001",
    classId: "c1",
    sectionId: "sec1",
    parentId: "p1",
    status: "active",
    admissionDate: "2023-04-01",
    avatar: "/female-student-1.jpg",
  },
  {
    id: "st2",
    userId: "u9",
    name: "James Wilson",
    email: "james.w@student.com",
    rollNumber: "STU002",
    classId: "c1",
    sectionId: "sec1",
    parentId: "p2",
    status: "active",
    admissionDate: "2023-04-01",
    avatar: "/male-student-1.jpg",
  },
  {
    id: "st3",
    userId: "u10",
    name: "Sophia Davis",
    email: "sophia.d@student.com",
    rollNumber: "STU003",
    classId: "c1",
    sectionId: "sec2",
    parentId: "p3",
    status: "active",
    admissionDate: "2022-04-01",
    avatar: "/female-student-2.png",
  },
  {
    id: "st4",
    userId: "u11",
    name: "Oliver Martinez",
    email: "oliver.m@student.com",
    rollNumber: "STU004",
    classId: "c2",
    sectionId: "sec3",
    parentId: "p4",
    status: "graduated",
    admissionDate: "2020-04-01",
    avatar: "/male-student-2.png",
  },
]

export const mockParents: Parent[] = [
  {
    id: "p1",
    userId: "u5",
    name: "Robert Thompson",
    email: "r.thompson@email.com",
    phone: "+1 555-2001",
    studentIds: ["st1"],
    avatar: "/parent-male-1.jpg",
  },
  {
    id: "p2",
    userId: "u12",
    name: "Patricia Wilson",
    email: "p.wilson@email.com",
    phone: "+1 555-2002",
    studentIds: ["st2"],
    avatar: "/parent-female-1.jpg",
  },
  {
    id: "p3",
    userId: "u13",
    name: "Mark Davis",
    email: "m.davis@email.com",
    phone: "+1 555-2003",
    studentIds: ["st3"],
    avatar: "/parent-male-2.jpg",
  },
  {
    id: "p4",
    userId: "u14",
    name: "Susan Martinez",
    email: "s.martinez@email.com",
    phone: "+1 555-2004",
    studentIds: ["st4"],
    avatar: "/parent-female-2.jpg",
  },
]

export const mockClasses: Class[] = [
  { id: "c1", name: "Grade 9", grade: 9, sections: [], subjects: ["sub1", "sub2", "sub3"], teacherId: "t1" },
  { id: "c2", name: "Grade 10", grade: 10, sections: [], subjects: ["sub1", "sub2", "sub4"], teacherId: "t2" },
  { id: "c3", name: "Grade 11", grade: 11, sections: [], subjects: ["sub1", "sub3", "sub5"], teacherId: "t3" },
  { id: "c4", name: "Grade 12", grade: 12, sections: [], subjects: ["sub2", "sub4", "sub5"], teacherId: "t4" },
]

export const mockSubjects: Subject[] = [
  { id: "sub1", name: "Mathematics", code: "MATH101", classIds: ["c1", "c2", "c3"], teacherId: "t1" },
  { id: "sub2", name: "English", code: "ENG101", classIds: ["c1", "c2", "c4"], teacherId: "t2" },
  { id: "sub3", name: "Physics", code: "PHY101", classIds: ["c1", "c3"], teacherId: "t1" },
  { id: "sub4", name: "Chemistry", code: "CHEM101", classIds: ["c2", "c4"], teacherId: "t3" },
  { id: "sub5", name: "Biology", code: "BIO101", classIds: ["c3", "c4"], teacherId: "t3" },
]

export const mockAttendance: Attendance[] = [
  { id: "a1", studentId: "st1", date: "2024-12-02", status: "present" },
  { id: "a2", studentId: "st2", date: "2024-12-02", status: "present" },
  { id: "a3", studentId: "st3", date: "2024-12-02", status: "absent", remarks: "Sick" },
  { id: "a4", studentId: "st4", date: "2024-12-02", status: "late", remarks: "Traffic" },
  { id: "a5", studentId: "st1", date: "2024-12-01", status: "present" },
  { id: "a6", studentId: "st2", date: "2024-12-01", status: "excused", remarks: "Medical appointment" },
]

export const mockExams: Exam[] = [
  {
    id: "e1",
    name: "Midterm Exam",
    type: "midterm",
    subjectId: "sub1",
    classId: "c1",
    date: "2024-10-15",
    maxMarks: 100,
  },
  { id: "e2", name: "Final Exam", type: "final", subjectId: "sub1", classId: "c1", date: "2024-12-15", maxMarks: 100 },
  { id: "e3", name: "Quiz 1", type: "quiz", subjectId: "sub2", classId: "c1", date: "2024-09-20", maxMarks: 20 },
  {
    id: "e4",
    name: "Assignment 1",
    type: "assignment",
    subjectId: "sub3",
    classId: "c1",
    date: "2024-09-25",
    maxMarks: 50,
  },
]

export const mockGrades: Grade[] = [
  { id: "g1", studentId: "st1", examId: "e1", subjectId: "sub1", marks: 92, grade: "A", remarks: "Excellent" },
  { id: "g2", studentId: "st2", examId: "e1", subjectId: "sub1", marks: 85, grade: "A-", remarks: "Very Good" },
  { id: "g3", studentId: "st3", examId: "e1", subjectId: "sub1", marks: 78, grade: "B+", remarks: "Good" },
  { id: "g4", studentId: "st1", examId: "e3", subjectId: "sub2", marks: 18, grade: "A", remarks: "Great work" },
]

export const mockSubscriptions: Subscription[] = [
  {
    id: "sub1",
    schoolId: "s1",
    plan: "premium",
    status: "active",
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    amount: 999,
  },
  {
    id: "sub2",
    schoolId: "s2",
    plan: "standard",
    status: "active",
    startDate: "2024-01-01",
    endDate: "2025-06-30",
    amount: 499,
  },
  {
    id: "sub3",
    schoolId: "s3",
    plan: "basic",
    status: "trial",
    startDate: "2024-11-01",
    endDate: "2025-01-15",
    amount: 0,
  },
  {
    id: "sub4",
    schoolId: "s4",
    plan: "premium",
    status: "expired",
    startDate: "2023-12-01",
    endDate: "2024-11-30",
    amount: 999,
  },
]

export const mockTimetable: TimetableEntry[] = [
  {
    id: "tt1",
    classId: "c1",
    sectionId: "sec1",
    subjectId: "sub1",
    teacherId: "t1",
    dayOfWeek: 1,
    startTime: "08:00",
    endTime: "09:00",
  },
  {
    id: "tt2",
    classId: "c1",
    sectionId: "sec1",
    subjectId: "sub2",
    teacherId: "t2",
    dayOfWeek: 1,
    startTime: "09:15",
    endTime: "10:15",
  },
  {
    id: "tt3",
    classId: "c1",
    sectionId: "sec1",
    subjectId: "sub3",
    teacherId: "t1",
    dayOfWeek: 1,
    startTime: "10:30",
    endTime: "11:30",
  },
  {
    id: "tt4",
    classId: "c1",
    sectionId: "sec1",
    subjectId: "sub1",
    teacherId: "t1",
    dayOfWeek: 2,
    startTime: "08:00",
    endTime: "09:00",
  },
  {
    id: "tt5",
    classId: "c1",
    sectionId: "sec1",
    subjectId: "sub4",
    teacherId: "t3",
    dayOfWeek: 2,
    startTime: "09:15",
    endTime: "10:15",
  },
]

export const dashboardStats = {
  superAdmin: {
    totalSchools: 24,
    activeSubscriptions: 18,
    totalRevenue: 156780,
    monthlyGrowth: 12.5,
    trialSchools: 6,
    expiredSubscriptions: 4,
  },
  admin: {
    totalStudents: 1250,
    totalTeachers: 85,
    totalClasses: 42,
    attendanceRate: 94.5,
    feeCollection: 89.2,
    pendingFees: 12500,
  },
  teacher: {
    assignedClasses: 4,
    totalStudents: 120,
    pendingGrades: 15,
    attendanceToday: 28,
    upcomingExams: 3,
  },
}

export const revenueData = [
  { month: "Jan", revenue: 12500, subscriptions: 18 },
  { month: "Feb", revenue: 14200, subscriptions: 20 },
  { month: "Mar", revenue: 13800, subscriptions: 19 },
  { month: "Apr", revenue: 15600, subscriptions: 22 },
  { month: "May", revenue: 16800, subscriptions: 24 },
  { month: "Jun", revenue: 18200, subscriptions: 26 },
  { month: "Jul", revenue: 17500, subscriptions: 25 },
  { month: "Aug", revenue: 19800, subscriptions: 28 },
  { month: "Sep", revenue: 21200, subscriptions: 30 },
  { month: "Oct", revenue: 22500, subscriptions: 32 },
  { month: "Nov", revenue: 24100, subscriptions: 34 },
  { month: "Dec", revenue: 25800, subscriptions: 36 },
]

export const attendanceData = [
  { day: "Mon", present: 92, absent: 5, late: 3 },
  { day: "Tue", present: 95, absent: 3, late: 2 },
  { day: "Wed", present: 88, absent: 8, late: 4 },
  { day: "Thu", present: 94, absent: 4, late: 2 },
  { day: "Fri", present: 90, absent: 6, late: 4 },
]

export const performanceData = [
  { subject: "Math", average: 85 },
  { subject: "English", average: 78 },
  { subject: "Physics", average: 82 },
  { subject: "Chemistry", average: 76 },
  { subject: "Biology", average: 80 },
]
