import type { Metadata } from "next";
import "./globals.css";
import { AppSidebar } from "@/components/layout/sidebar/app-sidebar"
import { SidebarProvider } from "@/components/ui/sidebar"
import {AppHeader}from '@/components/layout/app.header'
export const metadata: Metadata = {
  title: "School Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-sans antialiased' >
        <main >
          {children}
        </main>
      </body>
    </html>
  );
}
